import Head from 'next/head';
import styles from '../styles/Home.module.css';
import dynamic from 'next/dynamic';
import LayoutBox from '../components/nextjs-layout-box';

const ReactRemoteComponent = dynamic(() => import('remote/Nav'), {
  ssr: false,
});

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <LayoutBox>
        <main className={styles.main}>
          <h1 className={styles.title}>
            This is Next.js Host App
          </h1>
          <ReactRemoteComponent />
        </main>
      </LayoutBox>
    </div>
  );
}
