import Head from 'next/head'
import Image from 'next/image'
import dynamic from 'next/dynamic'

import styles from '../styles/Home.module.css'
import LayoutBox from '../components/nextjs-layout-box'
import Table from '../components/nextjs-table'
import Logo from '../public/nextjs.svg'

const tableData = [
  {
    company: 'Nutrien',
    state: 'Saskatchewan',
    country: 'Canada',
  },
  {
    company: 'Walmart',
    state: 'Delaware',
    country: 'USA',
  },
  {
    company: 'Microsoft',
    state: 'Washington',
    country: 'USA',
  },
]

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Next.js App</title>
        <meta name="description" content="Generated by Next.js App" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <LayoutBox>
        <Image width="200" src={Logo} alt="logo" />
        <Table data={tableData} />
      </LayoutBox>
    </div>
  )
}
