---
version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  ignore:
  - dependency-name: "@module-federation/nextjs-mf"
    versions:
    - 6.x
    - 7.x
  groups:
    minor-and-patch:
      update-types:
      - minor
      - patch
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
  groups:
    minor-and-patch:
      update-types:
      - minor
      - patch