import Head from 'next/head'
import dynamic from 'next/dynamic'

import styles from '../styles/Home.module.css'


const links = [
  { url: '/', label: 'Home' },
  { url: 'https://nextjs.org/', label: 'Learn more about Next.js' },
  {
    url: 'https://webpack.js.org/concepts/module-federation/',
    label: 'Learn more about Module Federation',
  },
]

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Next.js App</title>
        <meta name="description" content="Generated by Next.js App" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  )
}
